// ══════════════════════════════════════════════════════════════
// CHANGELOG (current major + renderer)
// ──────────────────────────────────────────────────────────────
// Classic <script src> (NOT a module / not fetched) so it works under file://
// in dev and over https in prod with zero CORS. The big HTML file stays small:
// on a version bump, add ONE entry at the TOP of CHANGELOG_CURRENT below
// (newest first) and bump the footer/#app-version — no need to touch the
// static markup.
//
// Each entry: { ver, date, tagEn?, tagEs?, en:[<li> inner HTML…], es:[…] }.
// Strings are template literals so the HTML's ' and " need no escaping. Keep the
// en[] and es[] arrays the same length (one bullet each). renderChangelog() builds
// the cards into #cl-list-host and is called on load + on every language switch.
//
// ⚠ Only the CURRENT major (v6.x) lives here — v5.x and older were moved to
// js/changelog-archive.js (v5.x on 2026-09-24, v4.x on 2026-08-02, older on 2026-07-24) and are
// concatenated below, so the rendered Changelog tab is unchanged. When v7.0.0 lands, move the
// v6 entries into the archive and start this array fresh.
// ══════════════════════════════════════════════════════════════
const CHANGELOG_CURRENT = [
  { ver: 'v6.2.1', date: '2026-10-06',
    en: [
      `<b>🏷 Tribe column in Offensive Targets</b>, right after Defender: the defender's tribe tag from the village database (hover for the full name). <b>Hidden by default</b> — tick it under 👁 Columns; the choice is remembered on this device. Click its header to sort by tribe.`,
      `<b>🔍 Filter by tribe.</b> The row filter gains a <b>Tribe</b> dropdown listing the tribes of the current targets (plus "(no tribe)" for barbarian / tribeless owners), and the text search now also matches the tribe tag. Like the other filters it is a view filter: the list, the exports and the plan are unaffected.`,
    ],
    es: [
      `<b>🏷 Columna Tribu en Objetivos Ofensivos</b>, justo después de Defensor: la etiqueta de la tribu del defensor según la base de datos de aldeas (pasa el ratón para ver el nombre completo). <b>Oculta por defecto</b> — márcala en 👁 Columnas; la elección se recuerda en este dispositivo. Clic en su cabecera para ordenar por tribu.`,
      `<b>🔍 Filtrar por tribu.</b> El filtro de filas gana un desplegable <b>Tribu</b> con las tribus de los objetivos actuales (más "(sin tribu)" para dueños bárbaros / sin tribu), y la búsqueda de texto ahora también coincide con la etiqueta de tribu. Como los demás filtros es un filtro de vista: la lista, las exportaciones y el plan no cambian.`,
    ],
  },
  { ver: 'v6.2.0', date: '2026-10-05',
    en: [
      `<b>↩ Returning Offs</b> (new Offensive tab). Import the Target Village Orders Exporter (incomingOrders.js) <b>JSON</b> exports — paste, or load several files at once — and see, per off village, whether its off is <b>in flight</b> 🚀, <b>returning</b> ↩ (with the time it is home again and a countdown) or already <b>home</b> 🏠, with its targets, tier and whether the Outbound Offs tab flags it too. Only real offs count: large / medium attacks, nobles and icons without a size; small attacks (fakes) and supports are ignored. One export of the enemy targets with "returning" ticked carries both the attacks in flight and the tribe's returns (listed on the attacked village, home village as origin).`,
      `<b>Two new Plan Offensive toggles, both on by default.</b> <b>Exclude ALL outbound offs</b> leaves out every village whose off is away (flagged on Outbound Offs, an attack still in flight, or an off still returning). <b>Include ALL returning offs in window</b> keeps a returning off usable, but only for targets it can still reach when launched after its home time — the plan marks those rows with ↩ (hover for the home time). An off still in flight is never used: its survivors are unknown until the hit. Both off = the plan exactly as before.`,
      `Batches merge: a command seen again (same id) replaces its older copy. An attack counts as in flight until the file holding it is removed or a newer export brings that command again — remove old files once their attacks have landed. A JSON imported in <b>Manage Offensive</b> feeds the tab automatically (its own line in the file list; ✕ Clear Import there removes it), and each file can be removed on its own.`,
      `The Plan Offensive off counts gain an <b>"excluded (outbound)"</b> bucket, and the warnings say how many offs were excluded or re-admitted from their home time.`,
    ],
    es: [
      `<b>↩ Offs de Vuelta</b> (nueva pestaña de Ofensiva). Importa las exportaciones <b>JSON</b> del Target Village Orders Exporter (incomingOrders.js) — pegadas, o varios archivos a la vez — y mira, por aldea ofensiva, si su off está <b>en vuelo</b> 🚀, <b>regresando</b> ↩ (con la hora a la que vuelve a casa y una cuenta atrás) o ya <b>en casa</b> 🏠, con sus objetivos, su nivel y si la pestaña Offs Fuera también la marca. Solo cuentan offs reales: ataques grandes / medianos, nobles e iconos sin tamaño; los ataques pequeños (fakes) y los apoyos se ignoran. Una sola exportación de los objetivos enemigos con "returning" marcado trae tanto los ataques en vuelo como los regresos de la tribu (listados en la aldea atacada, con la aldea de origen como casa).`,
      `<b>Dos casillas nuevas en Planear Ofensiva, ambas activadas por defecto.</b> <b>Excluir TODOS los offs fuera</b> deja fuera toda aldea cuyo off está fuera (marcada en Offs Fuera, un ataque todavía en vuelo o un off aún de regreso). <b>Incluir TODOS los offs de vuelta en ventana</b> mantiene utilizable un off que regresa, pero solo para objetivos a los que aún llega saliendo después de su hora de llegada a casa — el plan marca esas filas con ↩ (pasa el ratón para ver la hora). Un off todavía en vuelo nunca se usa: sus supervivientes se desconocen hasta el impacto. Ambas desactivadas = el plan exactamente como antes.`,
      `Los lotes se fusionan: una orden vista de nuevo (mismo id) sustituye a su copia anterior. Un ataque cuenta como en vuelo hasta que se quita el archivo que lo contiene o una exportación más reciente vuelve a traer esa orden — quita los archivos antiguos cuando sus ataques ya hayan impactado. Un JSON importado en <b>Gestionar Ofensiva</b> alimenta la pestaña automáticamente (su propia línea en la lista de archivos; ✕ Borrar Importación allí la quita), y cada archivo se puede quitar por separado.`,
      `El recuento de offs de Planear Ofensiva gana el apartado <b>"excluidas (fuera)"</b>, y los avisos indican cuántos offs se excluyeron o se readmitieron desde su hora de llegada a casa.`,
    ],
  },
  { ver: 'v6.1.3', date: '2026-10-04',
    en: [
      `<b>🔍 Full-pipeline review — bug-fix release.</b> A code review of every module found no regression from v6.x, but a number of long-standing gaps in the data feeding the planners and in a few engine corner cases. All of them are fixed here; the defaults of every planner stay the same except where listed.`,
      `<b>📂 Troop data loading.</b> A village present in two loaded files (all_troops + tribe_troops, a file dropped twice, a player who moved tribe) is now counted <b>once</b> (the later row wins; the status line reports the duplicates) instead of twice — before, a plan could order twice what the village owns. Columns are mapped by their header name (archer worlds and extra columns work; <code>tribe_defense</code> / <code>tribe_incoming</code> exports are read as garrison rows; a buildings export is rejected with a warning instead of being read as troops). Rows without a valid X|Y coordinate are skipped and counted, numbers with thousands separators or a <code>k</code> suffix are read correctly, JSON player names with commas no longer shift the columns, and player names / coordinates are always escaped in the tables. A garrison or buildings file dropped on its own is merged into the army already loaded instead of blanking it, and the Outbound Offs tab says how many villages have no garrison data.`,
      `<b>🛡 Defense.</b> Garrison data is now checked <b>per village</b>: when one tribe is loaded from an all_troops export (with garrison rows) and another from a plain tribe_troops file, the second tribe no longer reads as "0 available" and "100% outbound". A target's tribe tag follows the world database even when the owner left the tribe (the same-tribe gate applied to a stale tag). Plan Defense recomputes after the database arrives, after a new troop upload and after ✕ Clear (which now also empties the garrison indexes and the map). Plan Defense min/max distance are remembered. Manage Defense "remaining" only counts support coming from the target's planned senders.`,
      `<b>⚔ Offensive engine.</b> The split-off escort reservation is released when the noble train leaves from another village (before, one train could cost two offs and leave another target unassigned). Landing windows that cross midnight (e.g. 23:30–00:30) are handled consistently by the feasibility check, the late flag and Manage Offensive. Catapult attacks now honour Ignore Coordinates, Ignore Players, the sender area filters, MV pairs and the launch time (a catapult attack can no longer be planned in the past, and gets the late flag). Player Schedules ignore launch moments already in the past when grading, and the conqueror coordination pick honours schedules too. A village that only sent a fake in one offensive is no longer "spent" for the other offensives (fakes per village now count across offensives). Fakes require at least 1 ram. Blocked noble trains show ⏰ in their launch cell. The Offensive Targets footer subtracts the villages other offensives already use, and deleting a window group tells how many generated rows go with it.`,
      `<b>🕑 Server clock.</b> The server UTC offset is now <b>automatic</b> (follows Europe/Madrid summer / winter time, applied at the instant of each arrival) — leave the Settings field blank; a typed number still fixes it. Report ages use the server clock.`,
      `<b>💾 Storage &amp; start-up.</b> The offensive and Manage Offensive saves are compressed (much more room before the browser quota) and a full storage warns <b>once per session</b> instead of on every keystroke. A corrupted saved entry no longer blocks the whole start-up: the rest loads and a banner names what failed. The debug import no longer copies the development database into production storage; stale backups are cleaned. The compressed saves live under new storage keys: an older copy of the tool opened on the same browser storage keeps working on its own old copy and can never touch the new one.`,
      `<b>☁ Reports &amp; cloud.</b> Cloud requests time out (20 s reads, 45 s uploads) and fail over to the second host instead of hanging forever. Reports from another world are skipped (with a count) and the local report store is kept <b>per world</b>; switching world resets the shared data and ignores late responses; overlapping backups are both sent. A village conquered since the last report is no longer classified from the previous owner's army. A tribeless member in the troop file no longer hides every tribeless enemy's intel. Enemy Villages shows at most 200 rows with a debounced search, the map classifies only visible villages, and a failed share is reported instead of looking like a success.`,
      `<b>🌐 Language.</b> Spanish is applied to the footer and every popup at start-up; the load status line, power labels and badges are translated.`,
    ],
    es: [
      `<b>🔍 Revisión completa — versión de correcciones.</b> Una revisión de código de todos los módulos no encontró regresiones de la v6.x, pero sí varios huecos antiguos en los datos que alimentan a los planificadores y en algunos casos límite del motor. Todos se corrigen aquí; los valores por defecto de cada planificador no cambian salvo donde se indica.`,
      `<b>📂 Carga de tropas.</b> Una aldea presente en dos archivos cargados (all_troops + tribe_troops, un archivo soltado dos veces, un jugador que cambió de tribu) se cuenta ahora <b>una sola vez</b> (gana la fila posterior; la línea de estado indica los duplicados) en vez de dos — antes, un plan podía pedir el doble de lo que la aldea tiene. Las columnas se asignan por el nombre de su cabecera (funcionan los mundos con arqueros y columnas extra; las exportaciones <code>tribe_defense</code> / <code>tribe_incoming</code> se leen como filas de guarnición; una exportación de edificios se rechaza con un aviso en vez de leerse como tropas). Las filas sin coordenada X|Y válida se omiten y se cuentan, los números con separador de miles o sufijo <code>k</code> se leen bien, los nombres JSON con comas ya no desplazan las columnas, y los nombres de jugador / coordenadas se escapan siempre en las tablas. Un archivo de guarnición o de edificios soltado solo se fusiona con el ejército ya cargado en vez de vaciarlo, y la pestaña Offs Fuera indica cuántas aldeas no tienen datos de guarnición.`,
      `<b>🛡 Defensa.</b> Los datos de guarnición se comprueban ahora <b>por aldea</b>: si una tribu se carga desde un all_troops (con filas de guarnición) y otra desde un tribe_troops normal, la segunda ya no aparece con "0 disponible" y "100% fuera". La etiqueta de tribu de un objetivo sigue a la base de datos del mundo aunque el dueño haya dejado la tribu (el filtro de misma tribu usaba una etiqueta antigua). Planificar Defensa se recalcula al llegar la base de datos, tras una nueva subida de tropas y tras ✕ Limpiar (que ahora también vacía los índices de guarnición y el mapa). Se recuerdan la distancia mín/máx de Planificar Defensa. El "restante" de Gestionar Defensa solo cuenta el apoyo que viene de los remitentes planificados del objetivo.`,
      `<b>⚔ Motor ofensivo.</b> La reserva de escolta del split-off se libera cuando el tren de nobles sale desde otra aldea (antes, un tren podía costar dos offs y dejar otro objetivo sin asignar). Las ventanas de llegada que cruzan la medianoche (p. ej. 23:30–00:30) se tratan igual en la comprobación de viabilidad, la marca de tarde y Gestionar Ofensiva. Los ataques de catapultas respetan ahora Ignorar Coordenadas, Ignorar Jugadores, los filtros de zona de remitentes, las parejas MV y la hora de salida (ya no se planifica un ataque de catapultas en el pasado, y lleva la marca de tarde). Los Horarios Jugadores ignoran los momentos de salida ya pasados al puntuar, y la elección del off de coordinación del conquistador también respeta los horarios. Una aldea que solo envió un fake en una ofensiva ya no cuenta como "gastada" para las demás (los fakes por aldea se cuentan ahora entre ofensivas). Los fakes requieren al menos 1 ariete. Los trenes de nobles bloqueados muestran ⏰ en su celda de salida. El pie de Objetivos Ofensivos descuenta las aldeas que ya usan otras ofensivas, y al borrar un grupo de ventana se indica cuántas filas generadas se van con él.`,
      `<b>🕑 Hora del servidor.</b> El desfase UTC del servidor es ahora <b>automático</b> (sigue el horario de verano / invierno de Europa/Madrid, aplicado en el instante de cada llegada) — deja el campo de Ajustes en blanco; un número escrito lo sigue fijando. Las edades de los informes usan la hora del servidor.`,
      `<b>💾 Almacenamiento e inicio.</b> Los guardados de ofensiva y Gestionar Ofensiva van comprimidos (mucho más margen antes de la cuota del navegador) y un almacenamiento lleno avisa <b>una vez por sesión</b> en vez de a cada tecla. Una entrada guardada corrupta ya no bloquea todo el inicio: el resto se carga y un aviso indica qué falló. La importación de depuración ya no copia la base de datos de desarrollo al almacenamiento de producción; se limpian las copias antiguas. Los guardados comprimidos usan claves de almacenamiento nuevas: una copia antigua de la herramienta abierta sobre el mismo almacenamiento del navegador sigue funcionando con su propia copia antigua y nunca puede tocar la nueva.`,
      `<b>☁ Informes y nube.</b> Las peticiones a la nube caducan (20 s lecturas, 45 s subidas) y pasan al segundo servidor en vez de quedarse colgadas. Los informes de otro mundo se omiten (con recuento) y el almacén local de informes se guarda <b>por mundo</b>; cambiar de mundo reinicia los datos compartidos e ignora respuestas tardías; las copias de seguridad solapadas se envían ambas. Una aldea conquistada desde el último informe ya no se clasifica por el ejército del dueño anterior. Un miembro sin tribu en el archivo de tropas ya no oculta la información de todos los enemigos sin tribu. Aldeas Enemigas muestra como máximo 200 filas con búsqueda con retardo, el mapa solo clasifica las aldeas visibles, y un envío fallido se indica en vez de parecer un éxito.`,
      `<b>🌐 Idioma.</b> El español se aplica al pie y a todas las ventanas al iniciar; la línea de estado de carga, las etiquetas de poder y las insignias están traducidas.`,
    ],
  },
  { ver: 'v6.1.2', date: '2026-10-04',
    en: [
      `<b>⏰ Player Schedules</b> (Offensive Targets). A new popup lists every player in the loaded files with two launch-time ranges on the server clock: <b>preferred</b> and <b>blocked</b> (blank = none; a range may wrap past midnight). Generate Plan places each sender's attacks inside their preferred time when it can, outside their blocked time whenever possible, and still fills every slot — a launch forced into a blocked time is marked ⏰ on the row and listed in the warnings. Applies to offs, fakes, catapult attacks, escorts and noble senders; players without a schedule can launch any time. Hand-pinned off senders are never moved; a pinned noble sender keeps the assignment, but the schedule may pick which of their villages launches. Schedules are saved in this browser across sessions and independently of the files you load (a player set yesterday stays saved on a day their file isn't loaded — shown as "saved but not loaded") until you clear them in the popup.`,
      `<b>🎚 Player schedules</b> parameter (Plan Offensive): Preferred, then blocked (default) · Blocked only · Off.`,
    ],
    es: [
      `<b>⏰ Horarios Jugadores</b> (Objetivos Ofensivos). Una nueva ventana lista a todos los jugadores de los archivos cargados con dos rangos de hora de salida en la hora del servidor: <b>preferido</b> y <b>bloqueado</b> (en blanco = ninguno; un rango puede cruzar la medianoche). Al generar el plan, los ataques de cada remitente se colocan dentro de su horario preferido cuando se puede, fuera de su horario bloqueado siempre que sea posible, y aun así se rellenan todos los huecos — una salida forzada a un horario bloqueado se marca con ⏰ en la fila y aparece en los avisos. Se aplica a offs, fakes, ataques de catapultas, escoltas y remitentes de nobles; los jugadores sin horario pueden salir a cualquier hora. Los remitentes de off fijados a mano nunca se mueven; un remitente de nobles fijado conserva la asignación, pero el horario puede elegir desde cuál de sus aldeas sale. Los horarios se guardan en este navegador entre sesiones e independientemente de los archivos que cargues (un jugador configurado ayer sigue guardado el día que su archivo no está cargado — aparece como "guardado pero no cargado") hasta que los borres en la ventana.`,
      `Parámetro <b>🎚 Horarios Jugadores</b> (Planear Ofensiva): Preferido, luego bloqueado (por defecto) · Solo bloqueados · Desactivado.`,
    ],
  },
  { ver: 'v6.1.1', date: '2026-10-04',
    en: [
      `<b>🎚 Engine strategy parameters.</b> The choices the planners used to make silently are now named options, each a dropdown in 🎚 Parameters (central tab and the inline panel of its tab). <b>The first option of every list is marked "(default)" and is exactly what the tool did until now</b> — nothing changes unless you pick another. Plan Offensive: <b>Weaker-tier fallback</b> (Never · When the tier is empty — fall back to the next weaker tier, warned as downgraded), <b>Destroyer: rank among cat-offs</b> (Power · Catapults first), <b>Destroyer: when no off reaches the min cats</b> (Power · Most catapults · Leave unassigned) with <b>Destroyer fallback min cats</b>, <b>Split-off escort pick</b> (Closest · Strongest), <b>Fake source pool</b> (Offs, then escorts · Escorts, then offs · <b>Any village with rams</b> — every village with at least Rams per fake, whatever its tier and whether it sends a real off or not), <b>Catapult attack source</b> (Spread per player · Closest · Most catapults left). Plan Defense: <b>Sender pool fill order</b> (Per pool: home, then returning · All troops at home first). Manage Defense: <b>Order claiming a plan slot</b> (Earliest arrival · Closest amount).`,
      `<b>🎭 Morale strategy — Nearest targets first.</b> A fourth mode next to Highest morale first (the default), Balanced and By target points: targets closest to the centre of your off villages are filled first, list order among equals.`,
      `Warnings now quote the configured destroyer minimum instead of a fixed 101, and the "no fake source" warning no longer assumes Complete offs.`,
    ],
    es: [
      `<b>🎚 Parámetros de estrategia del motor.</b> Las decisiones que los planificadores tomaban en silencio son ahora opciones con nombre, cada una un desplegable en 🎚 Parámetros (pestaña central y panel de su pestaña). <b>La primera opción de cada lista lleva "(por defecto)" y es exactamente lo que la herramienta hacía hasta ahora</b> — nada cambia salvo que elijas otra. Planear Ofensiva: <b>Alternativa de tier inferior</b> (Nunca · Si el tier está vacío — recurrir al tier inferior, avisado como rebajado), <b>Destructor: orden entre offs con catapultas</b> (Poder · Catapultas primero), <b>Destructor: si ningún off llega al mínimo</b> (Poder · Más catapultas · Dejar sin asignar) con <b>Catapultas mín. de la alternativa</b>, <b>Escolta del split-off</b> (Más cercano · Más fuerte), <b>Fuente de fakes</b> (Offs, luego escoltas · Escoltas, luego offs · <b>Cualquier aldea con arietes</b> — todas las aldeas con al menos Arietes por fake, sea cual sea su tier y envíen o no un off real), <b>Origen de los ataques de catapultas</b> (Repartir por jugador · Más cercana · Más catapultas restantes). Planificar Defensa: <b>Orden de vaciado de los remitentes</b> (Por grupo: en casa, luego regresando · Primero todas las tropas en casa). Gestionar Defensa: <b>Orden al reclamar un hueco del plan</b> (Llegada más temprana · Cantidad más cercana).`,
      `<b>🎭 Estrategia de moral — Objetivos más cercanos primero.</b> Un cuarto modo junto a Mayor moral primero (el de por defecto), Equilibrado y Por puntos del objetivo: los objetivos más próximos al centro de tus aldeas off se rellenan antes, en orden de lista entre iguales.`,
      `Los avisos citan ahora el mínimo de catapultas configurado para voladoras en vez de un 101 fijo, y el aviso de "sin fuente de fake" ya no da por hecho offs Completa.`,
    ],
  },
  { ver: 'v6.1.0', date: '2026-10-04',
    en: [
      `<b>💾 Offensive plan slots (Plan Offensive).</b> Offensive plans now live in <b>save slots</b> — "Offensive 1", "Offensive 2", … — picked from a selector above the plan settings. The usual flow (load files → set targets → Generate Plan) fills the selected slot; <b>➕ New offensive</b> starts an empty second one next to it: change the targets, windows or settings and Generate Plan again — the engine only uses what the <b>other offensives left free</b>: an off sent there stays sent, nobles already on a train are gone, catapults already sending come off the budget, launch villages held for a noble stay held, and their senders don't fake here either. The hint line says how much the other offensives hold; the off counts footer gets an "in other offensives" bucket. Slots are frozen snapshots (their rows keep their own windows and dates), so reshaping the window groups for the next offensive never touches an earlier one. Rename a slot inline, delete it to free its villages; Export Unused Offs and Export Coordinates work across every offensive. Existing saves become "Offensive 1".`,
      `<b>Manage Offensive — all offensives together.</b> With two or more slots an <b>Offensive</b> selector in the header shows <b>All offensives</b> merged (rows aimed at the same target sit together, each row tagged with its slot) or one offensive alone; the incoming orders are matched against whatever is shown. The map and the exports follow the slot selected in Plan Offensive.`,
    ],
    es: [
      `<b>💾 Ranuras de plan ofensivo (Planear Ofensiva).</b> Los planes ofensivos viven ahora en <b>ranuras de guardado</b> — "Ofensiva 1", "Ofensiva 2", … — elegidas desde un selector sobre los ajustes del plan. El flujo de siempre (cargar archivos → fijar objetivos → Generar Plan) rellena la ranura seleccionada; <b>➕ Nueva ofensiva</b> abre una segunda vacía a su lado: cambia los objetivos, las ventanas o los ajustes y vuelve a Generar Plan — el motor solo usa lo que las <b>demás ofensivas dejaron libre</b>: un off enviado allí sigue enviado, los nobles ya en un tren se han ido, las catapultas que ya envían se descuentan del presupuesto, las aldeas de lanzamiento retenidas para un noble siguen retenidas, y sus remitentes tampoco hacen fakes aquí. La línea de ayuda dice cuánto retienen las demás ofensivas; el pie de recuento de offs gana una categoría "en otras ofensivas". Las ranuras son instantáneas congeladas (sus filas conservan sus ventanas y fechas), así que reorganizar los grupos de ventanas para la siguiente ofensiva nunca toca una anterior. Renombra una ranura en línea, bórrala para liberar sus aldeas; Exportar Offs Sin Usar y Exportar Coordenadas funcionan sobre todas las ofensivas. Los guardados existentes pasan a ser "Ofensiva 1".`,
      `<b>Gestionar Ofensiva — todas las ofensivas juntas.</b> Con dos o más ranuras, un selector <b>Ofensiva</b> en la cabecera muestra <b>Todas las ofensivas</b> fusionadas (las filas al mismo objetivo van juntas, cada fila etiquetada con su ranura) o una sola ofensiva; las órdenes entrantes se cotejan con lo que se muestra. El mapa y las exportaciones siguen la ranura seleccionada en Planear Ofensiva.`,
    ],
  },
  { ver: 'v6.0.4', date: '2026-10-04',
    en: [
      `<b>🏛 Buildings (Offensive Targets).</b> A new button left of Filter / Columns / Edit Selected Rows opens a popup with two checkbox columns: <b>Catapult target buildings</b> (what the per-attack picker of the Catapults column offers) and <b>Offensive target building</b> (what the Catapult Mode dropdown and its Edit Selected Rows buttons offer). Every building catapults can hit is available — Headquarters, Barracks, Stable, Workshop, Church, Watchtower, Academy, Smithy, Rally Point, Statue, Market, Timber Camp, Clay Pit, Iron Mine, Farm, Warehouse, Wall — and the defaults are exactly today's lists. A row already using a building you untick keeps it and still lists it in its own dropdown; the popup shows how many rows use each building. Remembered with the offensive plan; ↺ Reset defaults restores the original lists.`,
    ],
    es: [
      `<b>🏛 Edificios (Objetivos Ofensivos).</b> Un botón nuevo a la izquierda de Filtro / Columnas / Editar Filas Seleccionadas abre una ventana con dos columnas de casillas: <b>Edificios objetivo de catapulta</b> (lo que ofrece el selector por ataque de la columna Catapultas) y <b>Edificio objetivo de la ofensiva</b> (lo que ofrecen el desplegable Modo Catapulta y sus botones de Editar Filas Seleccionadas). Están todos los edificios que las catapultas pueden golpear — Edificio Principal, Cuartel, Cuadra, Taller, Iglesia, Torre de vigilancia, Academia, Herrería, Plaza de Reuniones, Estatua, Mercado, Leñador, Barrera, Mina de Hierro, Granja, Almacén, Muralla — y por defecto están marcados exactamente los de hoy. Una fila que ya usa un edificio que desmarques lo conserva y sigue listándolo en su propio desplegable; la ventana muestra cuántas filas usan cada edificio. Se recuerda con el plan ofensivo; ↺ Restablecer vuelve a las listas originales.`,
    ],
  },
  { ver: 'v6.0.3', date: '2026-10-04',
    en: [
      `<b>📊 Available Defense (filtered).</b> A third summary table under Plan Defense: the leftover defense <b>another plan could still draw on</b>. A village only counts while it could still send right now — it passes every sender hold (Ignore Coordinates / Players, the map-drawn area, the enemy-tribe radius, Ignore Village with Knight, the sender min def pop), lies inside the Def min/max distance of at least one target and, with the same-tribe rule on, shares a tribe with a target. The existing <b>Available Defense</b> table keeps showing everything left at home, holds included.`,
      `<b>▸ Collapsible summaries.</b> <b>Support per Player</b>, <b>Available Defense</b> and the new filtered table fold into click-to-open panels (collapsed by default — they're tall); the header line keeps the headline (players listed / def pop left), and the panels you open stay open across reloads.`,
      `<b>🏷 Tribes in the summaries.</b> When the loaded troop file spans two or more tribes, a <b>Tribes</b> selector above the summaries shows them <b>combined</b>, <b>separated</b> (one block per tribe, each with its own Total) or <b>one tribe only</b> — on es100 / es103 support can't cross tribes, so mixed numbers were misleading. With a single tribe nothing changes.`,
      `<b>🎚 Support only within the same tribe</b> — new Plan Defense parameter, <b>on</b> by default (the rule the engine always applied: both sides resolved in the world DB, same tag or the pair is barred). Switch it <b>off</b> on worlds that allow cross-tribe support: any target may then be supported and the "tribe unresolved" warnings go quiet.`,
    ],
    es: [
      `<b>📊 Defensa Disponible (filtrada).</b> Una tercera tabla resumen bajo Planificar Defensa: la defensa sobrante de la que <b>otro plan aún podría tirar</b>. Una aldea solo cuenta mientras aún podría enviar ahora mismo — pasa todos los filtros de remitente (Ignorar Coordenadas / Jugadores, el área dibujada en el mapa, el radio de tribus enemigas, Ignorar Pueblo con Paladín, la granja def. mín. del remitente), está dentro de la distancia def. mín./máx. de al menos un objetivo y, con la regla de misma tribu activa, comparte tribu con un objetivo. La tabla <b>Defensa Disponible</b> de siempre sigue mostrando todo lo que queda en casa, filtros incluidos.`,
      `<b>▸ Resúmenes plegables.</b> <b>Apoyo por Jugador</b>, <b>Defensa Disponible</b> y la nueva tabla filtrada se pliegan en paneles que se abren con un clic (cerrados por defecto — son altos); la línea de cabecera conserva el titular (jugadores listados / pob. def. libre), y los paneles que abras se quedan abiertos entre recargas.`,
      `<b>🏷 Tribus en los resúmenes.</b> Cuando el archivo de tropas cargado abarca dos o más tribus, un selector <b>Tribus</b> sobre los resúmenes las muestra <b>juntas</b>, <b>separadas</b> (un bloque por tribu, cada uno con su Total) o <b>una sola tribu</b> — en es100 / es103 el apoyo no puede cruzar tribus, así que los números mezclados confundían. Con una sola tribu nada cambia.`,
      `<b>🎚 Apoyo solo dentro de la misma tribu</b> — nuevo parámetro de Planificar Defensa, <b>activado</b> por defecto (la regla que el motor siempre aplicó: ambos lados resueltos en la BD del mundo, misma etiqueta o el par queda vetado). Desactívalo en mundos que permiten apoyo entre tribus: entonces se puede apoyar cualquier objetivo y los avisos de "tribu sin resolver" se callan.`,
    ],
  },
  { ver: 'v6.0.2', date: '2026-10-04',
    en: [
      `<b>🏰 Rally Point and Warehouse as catapult objectives.</b> Both buildings join the <b>Catapult Mode</b> dropdown (the building this target's off senders aim at — now Smithy / Farm / Rally Point / Warehouse / Wall; POWER still forces Wall) and the per-attack building picker of the <b>Catapults</b> column (Smithy / Farm / Rally Point / Warehouse / Timber Camp / Clay Pit / Iron Mine). The Edit Selected Rows modal offers them too, and they show up in the plan and every export like the other buildings.`,
    ],
    es: [
      `<b>🏰 Plaza de Reuniones y Almacén como objetivos de catapulta.</b> Ambos edificios se suman al desplegable <b>Modo Catapulta</b> (el edificio al que apuntan los remitentes de off de este objetivo — ahora Herrería / Granja / Plaza de Reuniones / Almacén / Muralla; POWER sigue forzando Muralla) y al selector de edificios por ataque de la columna <b>Catapultas</b> (Herrería / Granja / Plaza de Reuniones / Almacén / Leñador / Barrera / Mina de Hierro). El modal Editar Filas Seleccionadas también los ofrece, y aparecen en el plan y en todas las exportaciones como los demás edificios.`,
    ],
  },
  { ver: 'v6.0.1', date: '2026-10-03',
    en: [
      `<b>🐴 Ignore Village with Knight (Plan Defense).</b> A new checkbox next to <b>Prioritize Sending From Far Villages</b>: when on, any of your villages that <b>owns a knight</b> keeps all its defense home — it leaves the sender pool entirely (so it doesn't inflate its player's capacity share either), whether the knight is home or out. Ownership is read from the village's own troop row; a village that merely hosts another player's knight is not affected. Remembered with the rest of the defensive plan.`,
      `<b>📊 Available Defense.</b> Below <b>Support per Player</b> a second table lists, per player, the defense left <b>unassigned</b> after the plan — available minus sending for each unit, plus its total def pop — closed by a Total row. It follows the same availability rules as the table above (defense at home or incoming only, never above the village's own troops; owned troops when the file has no garrison data).`,
    ],
    es: [
      `<b>🐴 Ignorar Pueblo con Paladín (Planificar Defensa).</b> Una casilla nueva junto a <b>Priorizar Envío Desde Aldeas Lejanas</b>: activada, cualquier pueblo tuyo que <b>posea un paladín</b> se queda toda su defensa en casa — sale por completo del grupo de remitentes (así tampoco infla la cuota de capacidad de su jugador), esté el paladín en casa o fuera. La propiedad se lee de la propia fila de tropas del pueblo; un pueblo que solo aloja el paladín de otro jugador no se ve afectado. Se recuerda con el resto del plan defensivo.`,
      `<b>📊 Defensa Disponible.</b> Debajo de <b>Apoyo por Jugador</b>, una segunda tabla lista, por jugador, la defensa que queda <b>sin asignar</b> tras el plan — disponible menos enviado por cada unidad, más su población defensiva total — cerrada por una fila Total. Sigue las mismas reglas de disponibilidad que la tabla de arriba (solo defensa en casa o en camino, nunca por encima de las tropas propias del pueblo; tropas que posee cuando el archivo no tiene datos de guarnición).`,
    ],
  },
  { ver: 'v6.0.0', date: '2026-09-24',
    en: [
      `<b>🎚 Parameters.</b> A new <b>⚙ Settings → 🎚 Parameters</b> tab collects every threshold, default and limit the tool used to carry as a fixed number — 45 of them — so a tribe can tune the planners to its own doctrine without touching the code. Among them: the catapults an off needs to count as a destroyer's clearing off (101), the distance lead and per-village cap of the extra catapult attacks, the default nobles / catapult attacks of a new target, how many launch villages a noble sender keeps back and how big they must be, the Smithy level that makes a village snob-capable, the escort tier, whether a missing off tier may be filled by a stronger one, the size and source tier of fakes, the roster-balance weight, the small-garrison and packet floors of Plan Defense, the spy reserve per ram, the Snip / Support Packs defaults, the PM bracket budget, what the matchers treat as a fake, the Outbound Offs axe rule, the off / def village classification ratio, a departure safety margin and the server-offset fallback. The <b>Offensive Power Thresholds</b> moved here too. Rows in gold differ from their default; ↺ restores one, <b>Reset all</b> restores everything; values persist and ride along in the Export Data backup.`,
      `<b>🎚 …and on every tab that uses them.</b> By Villages, Outbound Offs, Tribe Timings, Plan Offensive, Plan Defense, Manage Offensive and Manage Defense each open with a collapsed <b>🎚 Parameters</b> panel holding just their own subset. They are views of the same values as the central tab — edit a number on either side and every panel, table and the next plan see it at once; a badge on the panel counts the values that differ from their default.`,
      `<b>⏱ Tolerances that did not exist before.</b> Four new parameters start at 0 (= the old behaviour) and add slack where the tool was strict: minutes an incoming may land outside its plan window and still match (Manage Offensive), minutes a plan row stays pending after its latest launch moment, the per-unit tolerance and arrival grace of the Manage Defense verdicts, plus the departure safety margin above, which every "can it still make it" check honours.`,
      `<b>🔧 Fixes.</b> The Edit Selected Rows modal seeded the catapult-attack count with 5 while the row toggle used 3 — both now follow the parameter. The Ver informe send / return estimates in Village Reports assumed es100's unit speeds; they now use the selected world's.`,
    ],
    es: [
      `<b>🎚 Parámetros.</b> Una nueva pestaña <b>⚙ Config. → 🎚 Parámetros</b> reúne todos los umbrales, valores por defecto y límites que la herramienta llevaba como número fijo — 45 — para que una tribu ajuste los planificadores a su propia doctrina sin tocar el código. Entre ellos: las catapultas que necesita una off para contar como off de limpieza de un destructor (101), la ventaja de distancia y el tope por aldea de los ataques de catapultas extra, los nobles / ataques de catapultas por defecto de un objetivo nuevo, cuántas aldeas de lanzamiento reserva un remitente de nobles y qué tamaño deben tener, el nivel de herrería que hace a una aldea capaz de noblar, el tier de la escolta, si un tier de off que falta puede cubrirse con uno más fuerte, el tamaño y el tier de origen de los fakes, el peso del reparto por plantilla, los mínimos de guarnición y de paquete de Planificar Defensa, la reserva de espías por ariete, los valores por defecto de Snip / Paquetes de Apoyo, el presupuesto de corchetes del MP, lo que los comparadores consideran fake, la regla de hachas de Offs Enviadas, la proporción que clasifica una aldea como off / def, un margen de seguridad de salida y el desfase horario de reserva. Los <b>Umbrales de Poder Ofensivo</b> también se han movido aquí. Las filas en dorado difieren de su valor por defecto; ↺ restaura una, <b>Restablecer todo</b> restaura todas; los valores se guardan y viajan en la copia de Exportar Datos.`,
      `<b>🎚 …y en cada pestaña que los usa.</b> Aldeas, Offs Enviadas, Tiempos de Tribu, Planificar Ofensiva, Planificar Defensa, Gestionar Ofensiva y Gestionar Defensa abren con un panel <b>🎚 Parámetros</b> plegado que contiene solo su propio subconjunto. Son vistas de los mismos valores que la pestaña central — cambia un número en cualquiera de los dos sitios y todos los paneles, tablas y el siguiente plan lo ven al instante; una insignia en el panel cuenta los valores que difieren de su valor por defecto.`,
      `<b>⏱ Tolerancias que antes no existían.</b> Cuatro parámetros nuevos empiezan en 0 (= el comportamiento anterior) y añaden holgura donde la herramienta era estricta: minutos que un ataque entrante puede llegar fuera de su ventana del plan y aun así coincidir (Gestionar Ofensiva), minutos que una fila del plan sigue pendiente tras su último momento de lanzamiento, la tolerancia por unidad y la gracia de llegada de los veredictos de Gestionar Defensa, más el margen de seguridad de salida anterior, que respetan todas las comprobaciones de «¿llega a tiempo?».`,
      `<b>🔧 Correcciones.</b> El modal Editar Filas Seleccionadas sembraba el número de ataques de catapultas con 5 mientras el interruptor de fila usaba 3 — ahora ambos siguen el parámetro. Las estimaciones de envío / regreso de Ver informe en Aldeas Enemigas asumían las velocidades de unidad de es100; ahora usan las del mundo seleccionado.`,
    ],
  },
];

// Full history = current major + the frozen archive, resolved at CALL time (not at
// load time) so changelog-archive.js can load in any order relative to this file —
// keeping the "inter-file order doesn't matter" invariant the rest of the app relies
// on. The typeof guard also keeps the page working (current major only) if the
// archive ever fails to load: a deploy that copies the HTML but misses the new js/
// file must not blank the tab.
function changelogEntries() {
  return CHANGELOG_CURRENT.concat(
    typeof CHANGELOG_ARCHIVE !== 'undefined' ? CHANGELOG_ARCHIVE : []);
}

// Build the changelog cards into #cl-list-host for the current language. Called on
// load and from changeLang(). Guarded so the headless test sandbox (no host element)
// is a no-op.
function renderChangelog() {
  if (typeof document === 'undefined' || !document.getElementById) return;
  const host = document.getElementById('cl-list-host');
  if (!host) return;
  const L = (typeof lang !== 'undefined' && lang === 'es') ? 'es' : 'en';
  const footer = L === 'es'
    ? 'v1.0.x – v1.3.x — versiones iniciales (anteriores al registro de versiones).'
    : 'v1.0.x – v1.3.x — initial releases (predate version tracking).';
  const cards = changelogEntries().map(e => {
    const tag = L === 'es' ? e.tagEs : e.tagEn;
    const date = e.date + (tag ? ' · ' + tag : '');
    const items = (e[L] || e.en).map(li => `<li>${li}</li>`).join('');
    return `<div class="cl-entry"><div class="cl-head"><span class="cl-ver">${e.ver}</span>`
      + `<span class="cl-date">${date}</span></div><ul class="cl-list">${items}</ul></div>`;
  }).join('');
  host.innerHTML = cards + `<p style="font-size:12px;color:#5a3a18;margin-top:6px;">${footer}</p>`;
}
